data:
  ticker: AAPL
  start: 2010-01-01
  end: 2025-01-01
  train_csv: data/{ticker}_train.csv
  test_csv:  data/{ticker}_test.csv
  split_date: 2018-01-01
  commission_rate: 0.001
  investment_capacity: 500

model:
  window_size: 12
  feature_dim: 14     # do not change unless indicators file changes

agent:
  learning_rate: 0.001
  batch_size: 20
  replay_memory_size: 10000
  epochs: 50
  gamma: 0.99
  target_update_freq: 200
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 0.9
