# Default hyperparameters (from Table 2 of the paper:contentReference[oaicite:5]{index=5} and additional settings)
window_size: 12            # time window length (L)
batch_size: 20             # training batch size
learning_rate: 0.001       # learning rate
epoch_count: 50            # number of training epochs (episodes)
commission_rate: 0.001     # commission fee rate per trade
investment_capacity: 500   # investment capacity (IC), in shares
initial_cash: dynamic      # initial wealth = IC * first close price (determined at runtime)
optimizer: RAdam           # optimizer algorithm
replay_memory_size: 10000  # experience replay buffer capacity
gamma: 0.99                # discount factor for future rewards
target_update_freq: 100    # target network update frequency (steps)
epsilon_start: 1.0         # initial epsilon for exploration
epsilon_end: 0.1           # minimum epsilon
epsilon_decay: 0.95        # epsilon decay factor per episode
